//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_previous_hospitalizations
    {
        public System.Guid patient_visit_id { get; set; }
        public System.Guid patient_id { get; set; }
        public string hospital_number { get; set; }
        public Nullable<System.DateTime> actual_visit_date_time { get; set; }
        public Nullable<System.DateTime> closure_date_time { get; set; }
        public string display_name { get; set; }
        public string visit_type { get; set; }
        public string visit_type_group { get; set; }
        public string charge_type { get; set; }
        public string primary_service { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
