//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_diagnosis
    {
        public System.Guid patient_visit_id { get; set; }
        public System.Guid patient_id { get; set; }
        public System.Guid patient_medical_coding_id { get; set; }
        public string hospital_number { get; set; }
        public Nullable<System.DateTime> actual_visit_date_time { get; set; }
        public string display_name { get; set; }
        public string visit_type { get; set; }
        public string charge_type { get; set; }
        public string coding_type { get; set; }
        public string coding_system { get; set; }
        public string code { get; set; }
        public string diagnosis { get; set; }
        public Nullable<System.DateTime> recorded_date_time { get; set; }
        public Nullable<bool> active_flag { get; set; }
        public Nullable<bool> primary_flag { get; set; }
        public Nullable<bool> current_visit_diagnostic_flag { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
