//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_previous_surgeries
    {
        public System.Guid previous_surgery_id { get; set; }
        public System.Guid patient_id { get; set; }
        public string hospital_number { get; set; }
        public string display_name { get; set; }
        public string previous_surgeries { get; set; }
        public Nullable<System.DateTime> creation_date_time { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
