//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_period
    {
        public int period_id { get; set; }
        public string period_text { get; set; }
        public System.DateTime period_date { get; set; }
        public Nullable<System.DateTime> processed_date { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string payment_period_status_rcd { get; set; }
        public Nullable<bool> active_flag { get; set; }
        public Nullable<System.DateTime> authorization_date { get; set; }
    }
}
